### ISSUE TITLE
The game crashes randomly

### ISSUE THREAD

**Issue by TheAirBlow** [QuantumFusionMC/DashLoader-Definitions#10]
**Describe the bug**
Minecraft crashes, but can be recovered by Not Enough Crashes.

**To Reproduce**
1. Just do anything you want (walk, fly, etc.)
4. With some chance Minecraft would crash

**Expected behavior**
Play normally without crashes

**Screenshots**
No screeenshots.

**Context (please complete the following information):**
- See the Crashy report: [click here](https://crashy.net/sYvtaibGMJ622lQEy49P)

**Comment by alphaqu** [comment]
Hi, this should be resolved in 4.0, let me know if it still happens. Cheers
