### ISSUE TITLE
JVM crash while loading server resource pack

### ISSUE THREAD

**Issue by forkiesassds** [QuantumFusionMC/DashLoader-Definitions#11]
**Describe the bug**
When loading server resource packs the client crashes with no error or a JVM crash

**To Reproduce**
1. Join a server requiring a custom resource pack
2. Accept the custom resource pack
3. Wait for it to download and to load
4. Game crashes

**Expected behavior**
The client shouldn't crash

**Screenshots**

**Context (please complete the following information):**
 - DashLoader Version 3.1.1
 - Minecraft Version 1.18.2

**Additional context**

**Comment by alphaqu** [comment]
Can you please update dashloader to a newer release?

**Comment by forkiesassds** [comment]
3.1.1 is the newest? I literally have the latest version

**Comment by alphaqu** [comment]
Hi, this should be resolved in 4.0, cheers.
