### ISSUE TITLE
Font issue when paired with Indium

### ISSUE THREAD

**Issue by uzervlad** [QuantumFusionMC/DashLoader-Definitions#14]
**Describe the bug**
When DashLoader is paired with Indium, the font appears to be broken

**Screenshots**
![image](https://user-images.githubusercontent.com/24654479/169345039-0b65aee3-b9a2-4272-b8b5-d28f5ab3123d.png)

**Context:**
 - Minecraft 1.18.2
 - DashLoader 3.1.1
 - Indium 1.0.3

**Additional context**
Reporting it here, since the logs contain no errors from Indium

**Logs:**
[latest.log](https://github.com/TeamQuantumFusion/DashLoader-Definitions/files/8731976/latest.log)

**Comment by JustSimplyKyle** [comment]
I doubt it's an indium problem, I can't reproduce it using pure indium, sodium, and dash

**Comment by uzervlad** [comment]
Can it possibly be a three-way incompatibility, since it only happens when both DashLoader and Indium are present?

What can I do to diagnose it further, except for disabling other mods one by one?

**Comment by alphaqu** [comment]
HI there. Can you please try a newer dashloader version? If the issue persists feel free to reopen the issue.
