### ISSUE TITLE
Add support for 1.19

### ISSUE THREAD

**Issue by SecretlyJealous** [QuantumFusionMC/DashLoader-Definitions#16]
Would you be able to update this mod to work on 1.19 whenever you get the time

**Comment by gliscowo** [comment]
You may watch our highly-trained professional developers do the job [here](https://www.youtube.com/watch?v=E6H74_P7UYA) and enjoy the rest of your day, while you wait, by looking at [this exquisit documentation](https://docs.quantumfusion.dev/rustaria/items/) for a completely unrelated game

**Comment by alphaqu** [comment]
Hi there, DashLoader 1.19 has been released! You may download it at our curseforge or modrinth.
