### ISSUE TITLE
dash loader incorrectly caching display value of a child model

### ISSUE THREAD

**Issue by walksanatora** [QuantumFusionMC/DashLoader-Definitions#19]
**Describe the bug**
earlier I was working on a data pack and i had the following json
```json
{
	"parent":"gun:item/awp",
	"display": {
		"firstperson_righthand": {
			"rotation": [0, 0, 0],
			"translation": [-10.1, 14, 5.614],
			"scale": [1, 1, 0.7]
		},
		"firstperson_lefthand": {
			"rotation": [0, 0, 0],
			"translation": [-8, 14, 5.614],
			"scale": [1, 1, 0.7]
		}
	}
}
```
In vanilla minecraft the model is placed in the top middle of the screen
when using fabric with dash loader the model is placed in the top right (the position of the parent model)

**To Reproduce**
1. create a model
2. create a child model and change it's display properties
3. child does not have updated display properties

**Expected behavior**
model is placed in proper location

**Context (please complete the following information):**
 - DashLoader Version: 4.0.0+1.19
 - Minecraft Version: fabric 1.19

**Comment by alphaqu** [comment]
Hi there! Can you please provide full logs when this happened?

**Comment by alphaqu** [comment]
Should be fixed in the next release.
