### ISSUE TITLE
EBE Compatibility?

### ISSUE THREAD

**Issue by piebaker** [QuantumFusionMC/DashLoader-Definitions#26]
After having a read-through pull request & issues, just wondering as to the current (1.19.1) compatibility status of EBE with Dashloader? 
Some pull requests have compatibility pulled in, but some issues have it as problematic.

**Comment by PweSol** [comment]
it's compatible

**Comment by rayzchen** [comment]
I've confirmed its compatible

**Comment by evhunter09** [comment]
It also works on 1.18.2 and 1.19, not tried it on 1.19.2

**Comment by piebaker** [comment]
Awesome. Cheers all
