### ISSUE TITLE
MoreCulling incompatability

### ISSUE THREAD

**Issue by Phoenix-Starlight** [QuantumFusionMC/DashLoader-Definitions#29]
**Describe the bug**
Sodium currently is broken, and renders in a way similar to xray. (Walls are absolutely transparent)
**To Reproduce**
1. Go to any world

**Expected behavior**
Not be xray-like and transparent

**Context (please complete the following information):**
 - DashLoader Version 4.1.2+1.19
 - Minecraft Version 1.19

**Full Logs**
[latest.log](https://github.com/TeamQuantumFusion/DashLoader/files/9449351/latest.log)

**Additional Context**
If Dashloader fails (F3+T) then everything behaves as normal.

**Comment by alphaqu** [comment]
Can you please isolate the issue? Sodium with DashLoader does not cause an incompatibility by my testing. This may be a different mod being incompatible or a 3 way incompatibility.

**Comment by AreaDenial** [comment]
I'm having an issue like this occur as well, I thought it was another mod at first but it seems Dashloader may be the culprit. These same chunks always become invisible after some time passes (perhaps when they're reloaded?). Exiting and reloading the world doesn't fix it, but pressing F3+T (clearing DashLoader's cache) does. Will do some testing later to try to isolate the issue, it might be completely unrelated to Sodium for all I know.
![chunks_normal](https://user-images.githubusercontent.com/32404366/188284670-a45e6be5-e027-445d-82e7-85c69cc176f7.png)
![chunks_broken](https://user-images.githubusercontent.com/32404366/188284676-2c108ed8-13f3-4a47-acd5-62b301219f2b.png)

**Comment by alphaqu** [comment]
My guess would be that this is a three way incompatibility with some stupid mod

**Comment by Phoenix-Starlight** [comment]
It may or may not be 4 way...

**Comment by Phoenix-Starlight** [comment]
This issue is invalid and closable. It appears to be that I forgot
Indium, which makes fabric rendering api, sodium and other mods that
utilize it work properly.

**Comment by Phoenix-Starlight** [comment]
I am forced to take what I said back because it happened again.

**Comment by Benonardo** [comment]
Also happened to me, especially on servers. It probably is a 3 way issue, but removing DashLoader has the least gameplay impact for now, so I am going to this. (The issue started to happen in 1.19.1)

**Comment by Phoenix-Starlight** [comment]
Not 3 way issue. 4 or 5 way issue. (Do resource packs count?)

Mods used:
Sodium
MoreCulling
Continuity
Fabric API
Indium
Dashloader

Resourcepacks used:
3D Redstone tweaks (requires Continuity and utilizes emissives) [here](https://modrinth.com/resourcepack/redstonetweaksresourcepack)
AquaHUD [here](https://modrinth.com/resourcepack/aquahud)
Log: [latest.log](https://github.com/TeamQuantumFusion/DashLoader/files/9501373/latest.log)
Reproduction steps:
1. Launch
2. Load resource packs in
3. Quit and re-launch. (So dashloader uses the cache)
4. Go to any world.

**Comment by PweSol** [comment]
I did mention this a long time ago here https://github.com/TeamQuantumFusion/DashLoader/pull/25#issuecomment-1201505842 but it seems like it was ignored. I'm running a plethora of performance mods as well, so it's most likely an incompatibility with some mod combination.

**Comment by Alexander020304** [comment]
I been having a similar issue.
![2022-11-01_16 57 12](https://user-images.githubusercontent.com/96150724/199339482-8c3d3f11-c406-4dfe-9b5b-37e12442c0cb.png)
[latest.log](https://github.com/TeamQuantumFusion/DashLoader/files/9913951/latest.log)

**Comment by primesonaldo** [comment]
> Also happened to me, especially on servers. It probably is a 3 way issue, but removing DashLoader has the least gameplay impact for now, so I am going to this. (The issue started to happen in 1.19.1)

Dude, it is because of MoreCulling and DashLoader. F3 + T fixes it (temporarily??)

**Comment by Phoenix-Starlight** [comment]
It only fixes because dashloader fails, so there is no 'boost' by
dashloader. Also it'll fail when dashloader naively allocates all
content causing OOM. Not really a good solution, per se.

**Comment by AreaDenial** [comment]
It definitely has to do with MoreCulling. The issue is fixed when I disable MoreCulling's "BlockState Culling" option, and when the option is re-enabled, the exact same invisible blocks become bugged again.

**Comment by FxMorin** [comment]
It's due to DashLoader somehow removing a final field from MultipartBakedModel. I didn't even think that would be possible without ASM.
If dashloader is some how removing that field, it may be doing it in other mods like Lithium. Causing it to recache the entire entity lists every time.
[MultipartBakedModel_cacheMixin](https://github.com/fxmorin/MoreCulling/blob/76602ca6ca0170ec08430a5c02458e9c51d3af68/src/main/java/ca/fxco/moreculling/mixin/models/MultipartBakedModel_cacheMixin.java#L33) This being missing should be impossible
