### ISSUE TITLE
DashLoader sometimes breaks fire animation

### ISSUE THREAD

**Issue by PweSol** [QuantumFusionMC/DashLoader-Definitions#3]
Reloading resource packs can sometimes break fire animation. Re-caching fixes it.

**Comment by alphaqu** [comment]
Please provide full logs.

**Comment by ondrani** [comment]
I have that problem too. Fire isn't animated.
Video: https://i.imgur.com/0pUb79q.mp4
[log.txt](https://github.com/TeamQuantumFusion/DashLoader-Definitions/files/8057552/log.txt)

**Comment by pluiedev** [comment]
Isn't that a long-established sodium issue? For example, stonecutters don't animate for me as well

**Comment by ondrani** [comment]
I have no problem with stonecutters. They are fine with dashloader on.
If I disable dashloader I have no problem with fire animation. 
Re-caching doesnt help.

**Comment by PweSol** [comment]
> Isn't that a long-established sodium issue? For example, stonecutters don't animate for me as well

Sodium doesn't cause this issue.

> I have no problem with stonecutters. They are fine with dashloader on. If I disable dashloader I have no problem with fire animation. Re-caching doesnt help.

Try deleting the dashloader-cache folder in your MC directory.

**Comment by PweSol** [comment]
> Please provide full logs.

I also apologize for not providing the logs. I haven't noticed your answer.

**Comment by PweSol** [comment]
I don't think I've encountered this problem on 4.0.0. I'll keep this open for some more time and if it doesn't happen, I'll assume this to be fixed and close the issue.
