### ISSUE TITLE
Dashloader runs into an Issue with loading

### ISSUE THREAD

**Issue by DanMeadWasTaken** [QuantumFusionMC/DashLoader-Definitions#34]
**Describe the bug**
Just dashloader hanging, then failing, game still technically continues - So doesn't "technically crash" But It's still an issue that should probably be fixed. <If need be, I can go through and figure out if it's a specific mod causing this.>

**To Reproduce**
Well, Use the mods listed as active in the log below.

**Expected behavior**
For it not to spit out that dashloader ran into an error and that I should check the logs

**Context (please complete the following information):**
 - DashLoader Version 4.1.3+1.19
 - Minecraft Version: 1.19.2

**Full Logs**
https://paste.ee/p/jECFM

**Additional context**
There is also a "crash" happening with puzzles lib, this is technically unrelated as that pops up in the log even when the dashloader crash doesn't happen, although I am making a report to them as well about that.

**Comment by alphaqu** [comment]
Hey i cannot access the paste, if you still experience issues please reopen this issue.
