### ISSUE TITLE
Fonts crash with Vanila Tweaks "Hunger Preview"

### ISSUE THREAD

**Issue by Kossesor** [QuantumFusionMC/DashLoader-Definitions#38]
**Describe the bug**
All letters in game crashes when you loading Vanilla Tweaks' Resource pack with Hunger Preview module

**Screenshots**
[https://imgur.com/a/HBwJrYw](url)

**Context (please complete the following information):**
 - DashLoader Version 1.4.5
 - Minecraft Version 1.16.5

**Additional context**
Hunger Preview works fine with MC 1.18.2

**Logs**
[https://pastebin.com/tKNhJegT](url)
password: _zT5PcQGC1z_

**Comment by alphaqu** [comment]
Hi, DashLoader is not maintained on 1.16.5, i can sadly not help you with the issue as that DashLoader is very outdated and buggy in the early days. Have a nice day!
