### ISSUE TITLE
Conflict with Monjangster [1.0.0]

### ISSUE THREAD

**Issue by TheKyuke** [QuantumFusionMC/DashLoader-Definitions#43]
**Describe the bug**
DashLoader loading screen override the Monjangster one (but still hearing the sound) with some font bug and Minecraft crashes when changing texture packs

**To Reproduce**
1. Launching the game with DashLoader installed
2. Change some texture pack for the game to crash

**Expected behavior**
Dashloader loading screen without errors and having the game not crashing when applying change to texture packs, if possible... letting users choose what loading screen they want to see

**Screenshots**
![image](https://user-images.githubusercontent.com/36053666/207743591-93e70436-1d89-4e6a-9251-e59798284337.png)

**Context (please complete the following information):**
 - Minecraft [1.19.2]
 - Fabric [0.14.11]
 - DashLoader Version [4.1.3]
 - Mojangster [1.0.0]

**Full Logs**
https://pastebin.com/iKTXAbKd

**Additional context**
Issue summited on Mojangster side too
https://github.com/mineblock11/mojangster/issues/2#issue-1497590889

**Comment by alphaqu** [comment]
Hey can you please provide the entire log and not just the crash section?

**Comment by alphaqu** [comment]
Hi, Mojangster is no longer maintained by mineblock11 and im not able to fix this on my side.
