### ISSUE TITLE
JVM Crash when trying to reload certain resource packs containing TTF Fonts (jemalloc.dll)

### ISSUE THREAD

**Issue by Blobanium** [QuantumFusionMC/DashLoader-Definitions#45]
**Describe the bug**
Technically, when you attempt to load/unload in a resource pack with Dashloader (Particularly with ones containing TTF Fonts) it will cause a JVM Crash. The Culprit seems to be jemalloc.dll if you check the problematic frame (Ive done some research about this dll in particular and from what i know this seems to be "Java extended memory allocation")

**To Reproduce**

1. Launch Minecraft
2. Navigate to the resource pack settings
3. Try to load in a pack containing a TTF Font ([This one should be a good example](https://github.com/TeamQuantumFusion/DashLoader/files/10329866/Bolbanu_font-pack.zip))
4. Minecraft crashes (You may have to load and unload it to get it to crash)

**Expected behavior**
It should properly load in the pack without issue

**Screenshots**
N/A

**Context (please complete the following information):**
 - DashLoader Version 4.1.3
 - Minecraft Version 1.19.2
 - Windows 11

**Additional context**
Crash log: [hs_err_pid22280.log](https://github.com/TeamQuantumFusion/DashLoader/files/10329868/hs_err_pid22280.log)

Also i have other mods installed But i am 100% certain it is dashloader causing this issue. Here's my mods folder just in case.
![image](https://user-images.githubusercontent.com/45613796/210191496-0b805532-09d2-4693-a11c-383573dead6b.png)

**Comment by alphaqu** [comment]
Hi there, the issue template wants you to provide the entire logs because its really hard for me to debug issues without the context of the entire loading process. Can you please provide your entire game logs when the crash occurs (And caching logs if you can). Thanks.

**Comment by Blobanium** [comment]
> Hi there, the issue template wants you to provide the entire logs because its really hard for me to debug issues without the context of the entire loading process. Can you please provide your entire game logs when the crash occurs (And caching logs if you can). Thanks.

[heres an entire log file that led up to the crash](https://github.com/TeamQuantumFusion/DashLoader/files/10333265/2023-01-01-1.log.gz)

Let me know if you need any more log files

**Comment by alphaqu** [comment]
Hi, are you able to test one of the newer 5.0 releases to see if it solves your issue? Your issue looks similar to one of the ones i fixed.

**Comment by alphaqu** [comment]
Hi, this should be fixed in 5.0
