### ISSUE TITLE
Crashes in 1.19.3

### ISSUE THREAD

**Issue by HhiPyrene** [QuantumFusionMC/DashLoader-Definitions#47]
**Describe the bug**
The game crashes while launching. If Dashloader removed, it launches normally.

**To Reproduce**
1. Launch the game.

**Expected behavior**
The game starts.

**Screenshots**

**Context (please complete the following information):**
 - DashLoader 5.0.0-alpha.3
 - Minecraft 1.19.3
 - Quilt Loader 0.18.1-beta.25

**Additional context**
Sometimes it can get into the main menu but the letters can't be displayed.
[crash-2023-01-04_23.47.15-client.txt](https://github.com/TeamQuantumFusion/DashLoader/files/10345788/crash-2023-01-04_23.47.15-client.txt)
[latest.log](https://github.com/TeamQuantumFusion/DashLoader/files/10345791/latest.log)

**Comment by alphaqu** [comment]
Hey, can you please try the 5.0.0-alpha.4 release to see if it fixes your issue?

**Comment by HhiPyrene** [comment]
Thanks, yes but not.  It didn't crashed again, but there's still some problem (The letters can't be displayed).  Then I launch the game for the second time, all the texture packs disabled.
[2023-01-05-6.log](https://github.com/TeamQuantumFusion/DashLoader/files/10346005/2023-01-05-6.log)
![huge_2023-01-05_00 46 45](https://user-images.githubusercontent.com/111572269/210609953-ea5d27c4-925b-4b16-b940-c87d6e7ae370.png)
![huge_2023-01-05_00 58 02](https://user-images.githubusercontent.com/111572269/210609955-7a8ecf46-5688-45e2-9852-ccf82214753c.png)

**Comment by HhiPyrene** [comment]
> Hey, can you please try the 5.0.0-alpha.4 release to see if it fixes your issue?

Thanks, yes but not.  It didn't crashed again, but there's still some problem (The letters can't be displayed).  Then I launch the game for the second time, all the texture packs disabled.
[2023-01-05-6.log](https://github.com/TeamQuantumFusion/DashLoader/files/10346005/2023-01-05-6.log)
![huge_2023-01-05_00 46 45](https://user-images.githubusercontent.com/111572269/210609953-ea5d27c4-925b-4b16-b940-c87d6e7ae370.png)
![huge_2023-01-05_00 58 02](https://user-images.githubusercontent.com/111572269/210609955-7a8ecf46-5688-45e2-9852-ccf82214753c.png)

**Comment by alphaqu** [comment]
Hey can you please try this version?
[things.zip](https://github.com/TeamQuantumFusion/DashLoader/files/10346222/things.zip)

**Comment by HhiPyrene** [comment]
> Hey can you please try this version?
> [things.zip](https://github.com/TeamQuantumFusion/DashLoader/files/10346222/things.zip)
> 

The problem that the characters errors appeared again when I launch the game again, but I noticed that it took a few time to get right. While I add the texture packs, the game can't load them, then I tried for more time and it worked. The game is able to play now, however the bug I described in this alpha version appears all the time I launch the game.
[latest.log](https://github.com/TeamQuantumFusion/DashLoader/files/10346480/latest.log)

**Comment by alphaqu** [comment]
Can you please join our discord server? Im having issues reproducing this issue https://discord.gg/APTKeqPb.

**Comment by alphaqu** [comment]
Also it seems like the log you sent me did not use the version i sent in the zip file.

**Comment by HhiPyrene** [comment]
> Also it seems like the log you sent me did not use the version i sent in the zip file.

Here's the log for that.
[2023-01-05-7.log](https://github.com/TeamQuantumFusion/DashLoader/files/10348860/2023-01-05-7.log)
