### ISSUE TITLE
[LAUNCH]: 1.19.2 - 5.0.0-alpha.6

### ISSUE THREAD

**Issue by PweSol** [QuantumFusionMC/DashLoader-Definitions#51]
### Version

dashloader-5.0.0-alpha.6+1.19.2

### Minecraft Version

1.19.2

### Entire Logs

https://mclo.gs/wycE5HZ

**Comment by alphaqu** [comment]
Im sadly not supporting the 1.19.2 version anymore as its quite a complicated version to maintain and has a decreasing number of users.
