### ISSUE TITLE
[LAUNCH]: dashloader-5.0.0-alpha.6+1.19.2 don't work on 1.19.2

### ISSUE THREAD

**Issue by fengyec2** [QuantumFusionMC/DashLoader-Definitions#52]
### Version

5.0.0-alpha.6

### Minecraft Version

1.19.2

### Entire Logs

minecraft.log: https://mclo.gs/6KlWxBy

### Additional Notes

dashloader-5.0.0-alpha.6+1.19.2 don't work on 1.19.2

**Comment by jonathansharpe** [comment]
same result for me, the game crashes upon startup

**Comment by theRookieCoder** [comment]
My guess is that some minecraft field got its obfuscated name changed?? Not sure why that happened because this should've been compiled for 1.19.2

Here is the error I get from my crash report:
```text
Caused by: java.lang.RuntimeException: dev.quantumfusion.hyphen.thr.HyphenException: 
Cause: Could not find a way to access "field_21483"
Suggestion: Try making the field public or add a getter

Object Stacktrace:
	at field field_21483 in class_1160
	at field field_4287 in class_804_<@DataNullablenull>
	at field thirdPersonLeftHand in DashModelTransformation_<@DataNullablenull>
	at field transformation in DashBasicBakedModel
```

**Comment by alphaqu** [comment]
Im sadly not supporting the 1.19.2 version anymore as its quite a complicated version to maintain and has a decreasing number of users.
