### ISSUE TITLE
[LAUNCH]: COM Except

### ISSUE THREAD

**Issue by Nostalgion** [QuantumFusionMC/DashLoader-Definitions#53]
### Version

5.0.0-alpha.6

### Minecraft Version

1.19.2

### Entire Logs

https://mclo.gs/LoQ1hJ0

### Additional Notes

Strange issue that can't find listed, it happens with latest dashloader for 1.19.2, 4.1.3 works perfectly fine. 
"[17:04:52] [Render thread/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile"
I cleared 50 gigabytes on my disk in an attempt to fix it, no dice, if this is something not on your end i apologize.

**Comment by alphaqu** [comment]
Im sadly not supporting the 1.19.2 version anymore as its quite a complicated version to maintain and has a decreasing number of users.
