### ISSUE TITLE
Maven is busted

### ISSUE THREAD

**Issue by sisby-folk** [QuantumFusionMC/DashLoader-Definitions#57]
quantumfusion.dev/maven has security issues, and notalpha.dev/maven is a 403. seems like a botched migration or something?

Either way, it's difficult to leverage dashloader as a developer using only the fat jar.

**Comment by alphaqu** [comment]
Hi yes, DashLoader has migrated to notalpha.dev but my nginx config decided to blow up. The issue should be resolved

**Comment by sisby-folk** [comment]
Thanks for that! I've also noticed that only `4.0.0` is available, would it be possible to publish `4.1.3+1.19`?

**Comment by alphaqu** [comment]
5.0 changed the maven group to notalpha.dev so there are a lot of versions under that and not quantumfusion.dev

I've gone ahead and uploaded older quantumfusion.dev releases.

Have a nice day!
