### ISSUE TITLE
Dashloader causes crash with CC: Restitched

### ISSUE THREAD

**Issue by RoboMico** [QuantumFusionMC/DashLoader-Definitions#6]
**Describe the bug**
It seems that Dashloader mis-caches some GUI classes of CC: Restitched, and the game crashes while opening a GUI of it. 

**To Reproduce**
1. Boot the game with Dashloader and CC: Restitched;
2. Create a new world;
3. Place down a computer and right click it;
4. The GUI of the computer is rendered incorrectly, then the game crashes.

**Context (please complete the following information):**
 - DashLoader 3.0-rc14
 - Minecraft 1.18.1 with Fabric 0.12.12 (API 0.46.4)
 - CC: Restitched 1.100.1
Other mods that might influence rendering:
- Sodium 0.4.0-alpha6 build14
- Indium 1.0.2-alpha2
If I missed something, the full mod list is included in the crash report.

**Additional context**
[crash-reports.zip](https://github.com/QuantumFusionMC/DashLoader-Definitions/files/8011673/crash-reports.zip)
Read `2022-02-06-4.log` from line 428.

**Comment by alphaqu** [comment]
Thank you for reporting! This is a known issue and is caused because of the aggressive dashloader shader cache.

**Comment by ghost** [comment]
In the meantime is there any temporary solution to make them play nice?

**Comment by alphaqu** [comment]
Hi there. This should be fixed as of 4.0+
