### ISSUE TITLE
[LAUNCH]: Crash on small 1.20 modpack

### ISSUE THREAD

**Issue by rdrpenguin04** [QuantumFusionMC/DashLoader-Definitions#64]
### Version

5.0.0-beta.1

### Minecraft Version

1.20

### Entire Logs

https://mclo.gs/ym0Esmd

### Additional Notes

I very well could be running incompatible mods without realizing it, but I haven't been able to determine that yet.

**Comment by alphaqu** [comment]
Hi there! This is an incompatibility with Better Nether and BCLib, the issue fully lies on their end. Ive tried contacting them in the past but they never wanted to cooperate on fixing the issue. Have a nice day!

**Comment by quiqueck** [comment]
Well, I am here to cooperate :D
Unfortunately, the error log does not give me any indication what is supposed to work differently. So any indication of what is tripping DahsLoader would be appreciated. :)
