### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by CrazyWolf13** [QuantumFusionMC/DashLoader-Definitions#68]
Hi,
I just wanted to request a version for 1.20.1, maybe you could port the 1.20 version.
Thank you for the great work

**Comment by ModEngineer** [comment]
I don't know if this is officially supported or stable, but the 1.20 version seems to work on 1.20.1. If it doesn't, it at least doesn't crash.

**Comment by CrazyWolf13** [comment]
> I don't know if this is officially supported or stable, but the 1.20 version seems to work on 1.20.1. If it doesn't, it at least doesn't crash.

Great, I didn't really test it with the old version, because I thought I once read only use the perfectly named version for the current mc version, but maybe that was another mod.

**Comment by alphaqu** [comment]
Ive gone ahead and added 1.20.1 as a compatible version.
