### ISSUE TITLE
Dashloader loads forever

### ISSUE THREAD

**Issue by ondrani** [QuantumFusionMC/DashLoader-Definitions#7]
Dashloader loads forever when changing resource pack. Maybe it's cause by some mod incompatibility mod no idea which mod.

 - DashLoader Version 3.0-rc14
 - Minecraft Version 1.18.1

[latest.log](https://github.com/TeamQuantumFusion/DashLoader-Definitions/files/8055632/latest.log)

**Comment by alphaqu** [comment]
HI there. Can you please try a newer dashloader version? If the issue persists feel free to reopen the issue.
