### ISSUE TITLE
Game crash when leaving servr

### ISSUE THREAD

**Issue by RealmKebab** [QuantumFusionMC/DashLoader-Definitions#70]
**Describe the bug**
The game crashes whenever you leave the server

**To Reproduce**
1. Play on a server with Sodium 0.5
2. Play for a bit (probably like 10 minutes)
3. Leave the server
4. Game crashes

**Expected behavior**
Game doesn't crash

**Screenshots**

**Context (please complete the following information):**
 - DashLoader Version 5.0.0-beta.1+1.20.0
 - Minecraft Version 1.20.1

**Additional context**
[Logs](https://mclo.gs/gLyhjAp)
[Crash Report](https://mclo.gs/71WdKTW)

**Comment by Paladynee** [comment]
I had the exact same crash. I tried re-installing everything.
The game seems to work fine at the first launch after installing. This might be because Dashloader caches content in this launch. Next launch, Dashloader initializes and causes the crash.

**Comment by alphaqu** [comment]
Duplicate issue: #63
