### ISSUE TITLE
[LAUNCH]: Dasheoader-Cache

### ISSUE THREAD

**Issue by DVH2006DK** [QuantumFusionMC/DashLoader-Definitions#72]
### Version

5.0.0-beta.1

### Minecraft Version

1.20+

### Entire Logs

https://api.mclo.gs/1/raw/l5S2kD4

### Additional Notes

I have been able to fix it by deleting the folder named ''dashloader-cache'' but for every time I want to relaunch/launch my client I will be forced to delete said folder again.

**Comment by alphaqu** [comment]
Duplicate issue: #63
