### ISSUE TITLE
[LAUNCH]: Dash loader 5.0.0_beta.1 1.20.1 crashing with sodium 0.5.0

### ISSUE THREAD

**Issue by ItsPoisonRed** [QuantumFusionMC/DashLoader-Definitions#74]
### Version

5.0.0_beta.1

### Minecraft Version

1.20.1

### Entire Logs

https://mclo.gs/xkeuMVq

### Additional Notes

Mods I'm using are just Dashloader, Fabric API, and Sodium. When I press launch, it takes a while and starts to open the game, but then it crashes. I can provide a video of it happening if you want. I don't think Dashloader can cache anything before it crashes.

**Comment by alphaqu** [comment]
Duplicate issue: #63
