### ISSUE TITLE
2.0 mod Errors in Log

### ISSUE THREAD

**Issue by greensad** [QuantumFusionMC/DashLoader-Definitions#8]
**Describe the bug**
2 Errors in log about 2.0 mods.

**To Reproduce**
1. Launch the game.

**Expected behavior**
Not throw concerning errors in log. 

**Context (please complete the following information):**
 - DashLoader Version 3.0-rc14
 - Minecraft Version 1.18.1

**Additional context**
Log: https://paste.ee/p/0ZBus

**Comment by alphaqu** [comment]
Hi 4.0 removes this console log. It is printed when it detects a mod using the old api, i dont know why i put it as error.
