### ISSUE TITLE
Sound queue filling up

### ISSUE THREAD

**Issue by UltraBlackLinux** [QuantumFusionMC/DashLoader-Definitions#9]
**Describe the bug**
With dashloader, the amount of playing (non ambient) sounds will increase over time. When it hits the cap of 255 sounds every sound is dropped even though not a singe one of the 255 sounds can be heard in game

**To Reproduce**
Play the game

**Context (please complete the following information):**
 - DashLoader Version 3.0-rc14
 - Minecraft Version 1.18.1

**Comment by ghost** [comment]
Possible temporary fix: https://modrinth.com/mod/audio-engine-tweaks

**Comment by alphaqu** [comment]
HI there. Can you please try a newer dashloader version? If the issue persists feel free to reopen the issue.
